### PR TITLE
Use a copying notice instead and remove the license

### PR DESCRIPTION
**Pull request by zorbyte**

### CODE REVIEW

**Comment by ktiy** [comment]
put copyright (c) 2020 somewhere so it looks official lmfao

**Comment by zorbyte** [comment]
🤦 oops

**Comment by ktiy** [comment]
LGTM

**Comment by zorbyte** [comment]
```
COPYRIGHT (C) 2020 itjk <cricket@piapiac.org> and zorbyte <zorbytee@gmail.com>

PROPRIETARY AND CONFIDENTIAL

Do not copy or redistribute any content of the content of this repository/codebase
```

**Comment by zorbyte** [comment]
wait there are typos

**Comment by ktiy** [comment]
oh

**Comment by zorbyte** [comment]
```
COPYRIGHT (C) 2020 itjk <cricket@piapiac.org> and zorbyte <zorbytee@gmail.com>

PROPRIETARY AND CONFIDENTIAL

Do not copy or redistribute any content of this repository/codebase
```

**Comment by zorbyte** [comment]
fixed it.

**Comment by ktiy** [comment]
lgtm again lol

**Pull request merged**
