### PR TITLE
Refactor in order to segregate ocl framework and modularise existing pieces

### PR DESCRIPTION
**Pull request by zorbyte**

### CODE REVIEW

**Review by ktiy — COMMENTED** [review]
on the license file, i would put "opolobot authors" then have a seperate authors file with like, each author and their emails

i guess this is not necessary for the bot itself since its private, but when OCL is in its own repo and pubic, maybe consider that (&& putting every contributor in the authors file or whatever)

not really too relevant; it all looks good

**Comment by zorbyte** [comment]
I don't think opolobot authors will hold any copyright though, since that doesn't refer to anyone, opolobot is a github organisation but opolobot authors is not

**Comment by zorbyte** [comment]
Since we are private now, our license should say something along the lines of

PROPRIETARY AND CONFIDENTIAL

AUTHORED BY opolobot (strictly including itjk and zorbyte)

**Comment by zorbyte** [comment]
and ocl would have MIT once it goes public

**Comment by ktiy** [comment]
that's true

anything holds copyright; even pseudonyms and fake names are allowed as long as it's enough information to correctly identify the author(s)

OCL could have "opolobot and contributors" in the LICENSE file and have a seperate AUTHORS or CONTRIBUTORS file listing all the authors & contributors

GNU recommends keeping records of which portions are written by whom in their own software [(source)](https://www.gnu.org/prep/maintain/html_node/Recording-Contributors.html) but i feel like that might be a little overboard considering git lol

**Comment by ktiy** [comment]
> Since we are private now, our license should say something along the lines of
> 
> PROPRIETARY AND CONFIDENTIAL
> 
> AUTHORED BY opolobot (strictly including itjk and zorbyte)

this sounds good to me as well, i dont know of any proprietary licenses since i dont usually work with proprietary software lmfao

**Comment by zorbyte** [comment]
> GNU recommends keeping records of which portions are written by whom in their own software (source) but i feel like that might be a little overboard considering git lol

Indeed, and its only us two working on the bot. If we ever expand the bot team to something like 5 I would think that would be appropriate

**Comment by zorbyte** [comment]
> this sounds good to me as well, i dont know of any proprietary licenses since i dont usually work with proprietary software lmfao

I would put this in a file called COPYING and delete LICENSE

**Comment by zorbyte** [comment]
I'd also add do not copy or redistribute

**Comment by ktiy** [comment]
> > GNU recommends keeping records of which portions are written by whom in their own software (source) but i feel like that might be a little overboard considering git lol
> 
> Indeed, and its only us two working on the bot. If we ever expand the bot team to something like 5 I would think that would be appropriate

that makes sense, i dont think its necessary at all for opolobot, was moreso for OCL when it goes open source in case anybody else contributes or whatever

**Comment by zorbyte** [comment]
It's useful to give credit to the respective authors of bot features in small but private teams. For OCL since its all MIT, we would just put the organisation so that if any legal disputes were to occur than the organisation (extending to the members) can effectively represent our claims.

**Comment by ktiy** [comment]
> > this sounds good to me as well, i dont know of any proprietary licenses since i dont usually work with proprietary software lmfao
> 
> I would put this in a file called COPYING and delete LICENSE

sounds good

**Comment by ktiy** [comment]
> It's useful to give credit to the respective authors of bot features in small but private teams. For OCL since its all MIT, we would just put the organisation so that if any legal disputes were to occur than the organisation (extending to the members) can effectively represent our claims.

got it; sounds good as well

**Pull request merged**
