### PR TITLE
key/value args & meme command

### PR DESCRIPTION
**Pull request by ktiy**
## key/value args
```go
args.New("[test=]", &parsers.String{}) // or whatever parser you'd like to use
```

## meme command
`'meme [image-url] [bottom=] [top=]`

example
image

### CODE REVIEW

**Review by zorbyte — CHANGES_REQUESTED** [review]
no light theme

**Review by zorbyte — APPROVED** [review]
jk, lgtm

**Comment by ktiy** [comment]
piss off

**Comment by zorbyte** [comment]
we are an professional develop:tm:

**Pull request merged**
